name: Export Docker Images

on:
  workflow_dispatch:

jobs:
  export-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Pull Docker images
        run: |
          docker pull minio/minio:latest

      - name: Save Docker images
        run: |
          mkdir images
          docker save minio/minio:latest \
            -o images/minio.tar

      - name: Compress
        run: |
          tar -czf docker-images.tar.gz images

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: docker-images.tar.gz
