name: Pull and Package NiFi
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull NiFi image
        run: docker pull apache/nifi:2.10.0

      - name: Save and compress image
        run: docker save apache/nifi:2.10.0 | gzip > nifi-2.10.0.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nifi-image
          path: nifi-2.10.0.tar.gz
          retention-days: 3
